# ==============================================================
# CI with GitHub Actions
# ==============================================================

name: Build

on:
  - push
  - pull_request

env:
  default-python: 3.12

jobs:
  testing:
    uses: renatoparedes/scikit-neuromsi/.github/workflows/tests.yml@00945144e500081b9519cd2a0067905a9b53a6fc

